import json
import logging
import httpx
from fastapi import HTTPException
from app.config import get_settings
from app.services.rag_pipeline import retrieve_context_rag

logger = logging.getLogger(__name__)

_ROUTER_SYSTEM = """\
You are a query classifier for a medical RAG system.
Classify the user query as either "General" or "Detailed".

Rules:
- "Detailed": The query requires deep analysis, summarization of long content, or \
complex cross-referencing across multiple topics or sections of a medical reference \
(e.g. "Summarize the differences between Type 1 and Type 2 diabetes treatments over \
the last decade.").
- "General": The query asks a simple factual question, needs a definition, asks about \
basic symptoms, or is general medical knowledge \
(e.g. "What are the common symptoms of asthma?").

Respond ONLY with valid JSON — no explanation, no extra text:
{"route": "Detailed"}  or  {"route": "General"}
"""


async def _route_query(query: str) -> bool:
    """LLM router — returns True for Detailed (complex), False for General.
    Defaults to False (General) on any failure.
    """
    try:
        raw = await _call_groq(
            [{"role": "user", "content": query}],
            _ROUTER_SYSTEM,
            temperature=0.0,
        )
        # Strip markdown fences if the model wraps the JSON
        cleaned = raw.strip().strip("```json").strip("```").strip()
        route = json.loads(cleaned).get("route", "General")
        is_complex = route == "Detailed"
        logger.info("LLM router: route=%s | query=%r", route, query[:80])
        return is_complex
    except Exception as exc:
        logger.warning("LLM router failed (%s) — defaulting to General", exc)
        return False


MEDICAL_ASSISTANT_SYSTEM = """You are Aarogyan's Medical Assistant — a supportive, knowledgeable, and empathetic AI health companion.

Your role:
- Provide accurate, evidence-based health INFORMATION for precautionary and educational purposes
- Help users understand symptoms, conditions, medications, and general wellness
- Simplify complex medical terminology into plain language
- Encourage healthy habits and timely professional consultation

STRICT BOUNDARIES — you must NEVER:
- Diagnose any medical condition
- Prescribe medications or recommend dosages
- Replace professional medical advice
- Make definitive statements about a user's health status

Always recommend consulting a qualified healthcare provider for medical decisions.
Be warm, non-clinical in tone, and especially patient-friendly for elderly users.

User medical profile context will be provided at the start — use it to personalise responses."""

_RAG_MEDICAL_SYSTEM = """\
You are Aarogyan's Medical Assistant — a supportive, evidence-based AI health companion.

You have been provided with relevant excerpts from trusted medical knowledge sources below.
Use ONLY the provided context to answer the user's question.
If the context does not contain enough information, say so honestly and recommend consulting a healthcare provider.

STRICT BOUNDARIES — you must NEVER:
- Diagnose any medical condition
- Prescribe medications or recommend dosages
- Replace professional medical advice

Respond in JSON with this exact structure:
{{
  "summary": "<1–2 sentence plain-language answer>",
  "details": "<fuller explanation with key facts drawn from the context>",
  "disclaimer": "This information is for educational purposes only. Please consult a qualified healthcare provider before making any medical decisions."
}}

--- Retrieved Medical Context ---
{context}
--- End of Context ---

{profile_section}"""

DOCUMENT_SUMMARY_SYSTEM = """You are a medical document analysis assistant inside Aarogyan, a health app.

Given OCR-extracted text from a medical document, produce a thorough analysis that any patient can understand.

Respond ONLY with a valid JSON object — no markdown, no code fences, no extra text:
{
  "document_type": "One of: Prescription, Blood Report, Radiology Report, Discharge Summary, Lab Report, or Other",
  "explanation": "A warm, clear, plain-language explanation of the entire document in 4-8 sentences. Explain what each test result, medication, or finding actually means for the patient in simple terms. Mention if any value is outside normal range and what that could mean.",
  "key_findings": ["Each important finding, medicine, abnormal value, or instruction as a short bullet string"],
  "confidence_score": <integer 0-100 reflecting how clearly interpretable the document text is — 90+ means clean readable text, 50-89 means some OCR noise but mostly clear, below 50 means heavy OCR errors or unclear content>,
  "disclaimer": "This analysis is generated by AI for informational purposes only and is not a substitute for professional medical advice, diagnosis, or treatment. Always consult a qualified healthcare provider before making any health decisions."
}

Rules:
- Keep the tone warm, encouraging, and non-alarming
- If any finding needs prompt medical attention, gently note it in key_findings with a ⚠️ prefix
- key_findings must be a JSON array of strings, minimum 1 item"""

EMOTIONAL_BUDDY_SYSTEM = """You are Orbz — Aarogyan's empathetic emotional wellness companion.

Your personality: warm, non-judgmental, gently curious, and supportive.
Your purpose: Help users process their emotions through compassionate conversation.

Guidelines:
- Ask how the user is feeling and genuinely listen
- Reflect emotions back to validate them
- Offer grounding techniques, breathing exercises, or gentle reframes when appropriate
- Never diagnose mental health conditions
- Never replace professional therapy
- If a user expresses serious distress or self-harm thoughts, gently encourage professional help

Also provide a mood_score: an integer from 1 (very distressed) to 10 (very positive/calm)
based on the emotional tone of the user's message.

IMPORTANT: Always respond in JSON format:
{
  "response": "your empathetic reply here",
  "mood_score": <integer 1-10>
}"""


async def _call_groq(messages: list[dict], system: str, temperature: float = 0.7) -> str:
    settings = get_settings()
    all_messages = [{"role": "system", "content": system}, *messages]

    async with httpx.AsyncClient(timeout=60.0) as client:
        response = await client.post(
            "https://api.groq.com/openai/v1/chat/completions",
            headers={
                "Authorization": f"Bearer {settings.groq_api_key}",
                "Content-Type": "application/json",
            },
            json={
                "model": settings.groq_model,
                "messages": all_messages,
                "temperature": temperature,
            },
        )
        try:
            response.raise_for_status()
        except httpx.HTTPStatusError as e:
            status = e.response.status_code
            logger.error("Groq error %s: %s", status, e.response.text)
            if status == 429:
                raise HTTPException(status_code=429, detail="AI service is busy. Please wait a moment and try again.")
            if status in (401, 403):
                raise HTTPException(status_code=503, detail="AI service auth error.")
            raise HTTPException(status_code=502, detail=f"AI service error: {status}")
        data = response.json()
        return data["choices"][0]["message"]["content"]


async def _chat_with_rag(
    user_message: str,
    history: list[dict],
    profile_context: str,
    is_complex: bool = False,
) -> str:
    """RAG-augmented chat: retrieve context then synthesise with Groq.

    General  (is_complex=False): top-8 chunks, no reranker — fast.
    Detailed (is_complex=True):  top-8 fetch → cross-encoder rerank → top-3 — accurate.
    """
    top_k_return = 3 if is_complex else 8
    context_str, sources = await retrieve_context_rag(
        user_message, is_complex=is_complex, top_k_return=top_k_return
    )
    logger.info(
        "RAG retrieved %d source(s); context length=%d (reranker=%s)",
        len(sources), len(context_str), is_complex,
    )

    if not context_str:
        logger.warning("RAG returned no context — falling back to plain LLM")
        return await _chat_plain(user_message, history, profile_context)

    profile_section = ""
    if profile_context:
        profile_section = f"--- User Health Profile ---\n{profile_context}"

    system = _RAG_MEDICAL_SYSTEM.format(
        context=context_str,
        profile_section=profile_section,
    )

    messages = [*history, {"role": "user", "content": user_message}]
    raw = await _call_groq(messages, system, temperature=0.2)

    # Parse structured JSON and format for the Flutter UI
    try:
        data = json.loads(raw)
        summary = data.get("summary", "")
        details = data.get("details", "")
        disclaimer = data.get("disclaimer", "")

        parts = []
        if summary:
            parts.append(summary)
        if details:
            parts.append(details)
        if sources:
            parts.append(f"*Sources: {', '.join(sources)}*")
        if disclaimer:
            parts.append(f"\n_{disclaimer}_")

        return "\n\n".join(parts)
    except (json.JSONDecodeError, AttributeError):
        return raw


async def _chat_plain(
    user_message: str,
    history: list[dict],
    profile_context: str,
) -> str:
    """Plain LLM chat without RAG (fallback when Qdrant returns nothing)."""
    system = MEDICAL_ASSISTANT_SYSTEM
    if profile_context:
        system += f"\n\n--- User Health Profile ---\n{profile_context}"
    messages = [*history, {"role": "user", "content": user_message}]
    return await _call_groq(messages, system)


async def chat_with_ai(
    user_message: str,
    history: list[dict],
    profile_context: str,
) -> str:
    is_complex = await _route_query(user_message)
    return await _chat_with_rag(user_message, history, profile_context, is_complex=is_complex)


async def summarise_document(ocr_text: str) -> dict:
    messages = [{"role": "user", "content": f"Please analyse this medical document and respond in the required JSON format:\n\n{ocr_text}"}]
    raw = await _call_groq(messages, DOCUMENT_SUMMARY_SYSTEM, temperature=0.2)
    try:
        cleaned = raw.strip().removeprefix("```json").removeprefix("```").removesuffix("```").strip()
        data = json.loads(cleaned)
        # Ensure confidence_score is a clamped integer
        data["confidence_score"] = max(0, min(100, int(data.get("confidence_score", 70))))
        # Ensure key_findings is always a list
        if not isinstance(data.get("key_findings"), list):
            data["key_findings"] = [str(data.get("key_findings", ""))]
        return data
    except (json.JSONDecodeError, ValueError, TypeError):
        return {
            "document_type": "Unknown",
            "explanation": raw,
            "key_findings": [],
            "confidence_score": 50,
            "disclaimer": "This analysis is generated by AI for informational purposes only and is not a substitute for professional medical advice.",
        }


async def emotional_buddy_respond(user_text: str) -> tuple[str, int]:
    """Returns (buddy_reply_text, mood_score)."""
    messages = [{"role": "user", "content": user_text}]
    raw = await _call_groq(messages, EMOTIONAL_BUDDY_SYSTEM)

    try:
        data = json.loads(raw)
        reply = data.get("response", raw)
        mood_score = int(data.get("mood_score", 5))
        mood_score = max(1, min(10, mood_score))
    except (json.JSONDecodeError, ValueError):
        reply = raw
        mood_score = 5

    return reply, mood_score
