"""
PDF export service — generates a full consultation PDF report.
Uses fpdf2 for clean, structured output.
"""
import io
import os
import logging
import httpx
from fpdf import FPDF
from datetime import datetime
from typing import Any

logger = logging.getLogger(__name__)

# Core fonts (Helvetica etc.) only support latin-1.
# Replace common Unicode punctuation with safe ASCII equivalents.
_UNICODE_MAP = str.maketrans({
    "\u2014": "-",   # em dash
    "\u2013": "-",   # en dash
    "\u2018": "'",   # left single quotation mark
    "\u2019": "'",   # right single quotation mark
    "\u201c": '"',   # left double quotation mark
    "\u201d": '"',   # right double quotation mark
    "\u2022": "*",   # bullet
    "\u2026": "...", # ellipsis
})

def _s(text: str) -> str:
    """Sanitize text for latin-1 fpdf core fonts."""
    return text.translate(_UNICODE_MAP).encode("latin-1", errors="replace").decode("latin-1")


class AarogyanPDF(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 16)
        self.set_text_color(26, 107, 90)  # Primary teal
        self.cell(0, 12, _s("Aarogyan - Consultation Report"), align="C", new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(26, 107, 90)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(107, 114, 128)
        self.cell(0, 10, _s(f"Page {self.page_no()} | Generated by Aarogyan | {datetime.now().strftime('%d %b %Y')}"), align="C")

    def section_title(self, title: str):
        self.set_font("Helvetica", "B", 13)
        self.set_fill_color(232, 245, 240)  # Soft mint
        self.set_text_color(26, 107, 90)
        self.cell(0, 10, _s(f"  {title}"), fill=True, new_x="LMARGIN", new_y="NEXT")
        self.ln(2)

    def field_row(self, label: str, value: str):
        label_w = 45
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(26, 26, 46)
        self.set_x(self.l_margin)  # always start from left margin regardless of prior state
        self.cell(label_w, 7, _s(label + ":"), new_x="RIGHT", new_y="LAST")
        self.set_font("Helvetica", "", 10)
        self.set_text_color(51, 51, 51)
        self.multi_cell(self.epw - label_w, 7, _s(str(value) if value is not None else "-"))

    def doc_link_row(self, name: str, url: str):
        """Render a document row with a wrapped, clickable URL."""
        # File name line
        self.set_font("Helvetica", "", 9)
        self.set_text_color(80, 80, 80)
        self.set_x(self.l_margin + 4)
        self.cell(0, 6, _s(f"\u2022 {name}"), new_x="LMARGIN", new_y="NEXT")
        if url:
            # Clickable "View Document" label + wrapped URL on next line
            self.set_x(self.l_margin + 8)
            self.set_font("Helvetica", "U", 8)
            self.set_text_color(26, 107, 90)
            safe_url = url if url.startswith("http") else ""
            self.cell(0, 5, _s("View Document"), link=safe_url, new_x="LMARGIN", new_y="NEXT")
            # URL text wrapped — helps users who copy from PDF
            self.set_font("Helvetica", "I", 7)
            self.set_text_color(120, 120, 120)
            self.set_x(self.l_margin + 8)
            self.multi_cell(self.epw - 8, 4, _s(url))
        self.set_text_color(26, 26, 46)

    def divider(self):
        self.set_draw_color(200, 220, 215)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(3)


async def generate_consultation_pdf(
    consultation: dict[str, Any],
    sessions: list[dict[str, Any]],
) -> bytes:
    pdf = AarogyanPDF(orientation="P", unit="mm", format="A4")
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # Consultation header
    pdf.section_title("Consultation Overview")
    pdf.field_row("Name", consultation.get("name", ""))
    pdf.field_row("Start Date", consultation.get("start_date", ""))
    if consultation.get("notes"):
        pdf.field_row("Notes", consultation["notes"])
    pdf.ln(4)

    if not sessions:
        pdf.set_font("Helvetica", "I", 10)
        pdf.cell(0, 8, _s("No sessions recorded."), new_x="LMARGIN", new_y="NEXT")
    else:
        for i, session in enumerate(sessions, start=1):
            pdf.section_title(f"Session {i} - {session.get('visit_date', 'Unknown Date')}")
            pdf.field_row("Symptoms", session.get("symptoms", ""))
            pdf.field_row("Diagnosis", session.get("diagnosis", ""))
            pdf.field_row("Medications", session.get("medications", ""))
            pdf.field_row("Doctor Notes", session.get("doctor_notes", ""))

            # Documents
            docs = session.get("session_documents", [])
            if docs:
                pdf.set_font("Helvetica", "B", 10)
                pdf.set_text_color(26, 26, 46)
                pdf.cell(0, 7, _s("Attached Documents:"), new_x="LMARGIN", new_y="NEXT")
                for doc in docs:
                    name = doc.get("file_name", "Unknown file")
                    url = doc.get("public_url", "") or ""
                    ext = os.path.splitext(name)[1].lower()

                    # Try embedding images directly into the PDF
                    embedded = False
                    if ext in (".jpg", ".jpeg", ".png") and url.startswith("https://"):
                        try:
                            async with httpx.AsyncClient(timeout=15.0) as client:
                                img_resp = await client.get(url)
                                img_resp.raise_for_status()
                            img_bytes = img_resp.content
                            img_io = io.BytesIO(img_bytes)
                            # Reserve space and embed; max width = 160mm, keep aspect
                            pdf.set_font("Helvetica", "I", 9)
                            pdf.set_text_color(80, 80, 80)
                            pdf.set_x(pdf.l_margin + 4)
                            pdf.cell(0, 6, _s(f"\u2022 {name} (embedded)"), new_x="LMARGIN", new_y="NEXT")
                            pdf.image(img_io, x=pdf.l_margin + 8, w=min(160, pdf.epw - 8))
                            pdf.ln(3)
                            embedded = True
                        except Exception as fetch_err:
                            logger.warning("Could not embed image %s: %s", name, fetch_err)

                    if not embedded:
                        pdf.doc_link_row(name, url)

                pdf.set_text_color(26, 26, 46)

            if i < len(sessions):
                pdf.divider()

        pdf.ln(4)

    # Footer note
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(107, 114, 128)
    pdf.multi_cell(
        0, 6,
        _s(
            "This document is a personal health record exported from Aarogyan and is not a medical certificate. "
            "Always consult a qualified healthcare professional for medical decisions."
        ),
    )

    return bytes(pdf.output())
