"""
PDF export service — generates a full consultation PDF report.
Uses fpdf2 for clean, structured output.
"""
from fpdf import FPDF
from datetime import datetime
from typing import Any


class AarogyanPDF(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 16)
        self.set_text_color(26, 107, 90)  # Primary teal
        self.cell(0, 12, "Aarogyan — Consultation Report", align="C", new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(26, 107, 90)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(107, 114, 128)
        self.cell(0, 10, f"Page {self.page_no()} | Generated by Aarogyan | {datetime.now().strftime('%d %b %Y')}", align="C")

    def section_title(self, title: str):
        self.set_font("Helvetica", "B", 13)
        self.set_fill_color(232, 245, 240)  # Soft mint
        self.set_text_color(26, 107, 90)
        self.cell(0, 10, f"  {title}", fill=True, new_x="LMARGIN", new_y="NEXT")
        self.ln(2)

    def field_row(self, label: str, value: str):
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(26, 26, 46)
        self.cell(45, 7, label + ":", new_x="RIGHT", new_y="LAST")
        self.set_font("Helvetica", "", 10)
        self.set_text_color(51, 51, 51)
        self.multi_cell(0, 7, value or "—")

    def divider(self):
        self.set_draw_color(200, 220, 215)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(3)


async def generate_consultation_pdf(
    consultation: dict[str, Any],
    sessions: list[dict[str, Any]],
) -> bytes:
    pdf = AarogyanPDF(orientation="P", unit="mm", format="A4")
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # Consultation header
    pdf.section_title("Consultation Overview")
    pdf.field_row("Name", consultation.get("name", ""))
    pdf.field_row("Start Date", consultation.get("start_date", ""))
    if consultation.get("notes"):
        pdf.field_row("Notes", consultation["notes"])
    pdf.ln(4)

    if not sessions:
        pdf.set_font("Helvetica", "I", 10)
        pdf.cell(0, 8, "No sessions recorded.", new_x="LMARGIN", new_y="NEXT")
    else:
        for i, session in enumerate(sessions, start=1):
            pdf.section_title(f"Session {i} — {session.get('visit_date', 'Unknown Date')}")
            pdf.field_row("Symptoms", session.get("symptoms", ""))
            pdf.field_row("Diagnosis", session.get("diagnosis", ""))
            pdf.field_row("Medications", session.get("medications", ""))
            pdf.field_row("Doctor Notes", session.get("doctor_notes", ""))

            # Documents
            docs = session.get("session_documents", [])
            if docs:
                pdf.set_font("Helvetica", "B", 10)
                pdf.set_text_color(26, 26, 46)
                pdf.cell(0, 7, "Attached Documents:", new_x="LMARGIN", new_y="NEXT")
                for doc in docs:
                    pdf.set_font("Helvetica", "", 9)
                    pdf.set_text_color(80, 80, 80)
                    name = doc.get("file_name", "Unknown file")
                    url = doc.get("public_url", "")
                    pdf.cell(0, 6, f"  • {name}", new_x="LMARGIN", new_y="NEXT")
                    if url:
                        pdf.set_text_color(26, 107, 90)
                        pdf.cell(0, 5, f"    {url}", new_x="LMARGIN", new_y="NEXT")
                pdf.set_text_color(26, 26, 46)

            if i < len(sessions):
                pdf.divider()

        pdf.ln(4)

    # Footer note
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(107, 114, 128)
    pdf.multi_cell(
        0, 6,
        "This document is a personal health record exported from Aarogyan and is not a medical certificate. "
        "Always consult a qualified healthcare professional for medical decisions.",
    )

    return bytes(pdf.output())
